### ISSUE TITLE
Help me

### ISSUE THREAD

**Issue by AyzrixYTB** [poggit-orphanage/EssentialsPE#11]
**Description**
How to change the time format ? Month , Day , ...

**Versions**
• PocketMine Version: 3.2.1
• EssentialsPE Version: 2.1.0
• Game Version: PE / Windows 10 1.6.0

**Comment by Ifera** [comment]
What time format?

**Comment by Ifera** [comment]
What does time format have to do with this plugin?

**Comment by AyzrixYTB** [comment]
The hour and date for Ban and Mute

**Comment by AyzrixYTB** [comment]
Wath do you closed ...

**Comment by Ifera** [comment]
Please refer to wiki.
https://github.com/LegendOfMCPE/EssentialsPE/wiki/Commands-List
