### ISSUE TITLE
Disable auto update by default

### ISSUE THREAD

**Issue by ZizzyZizzy** [poggit-orphanage/EssentialsPE#3]
For the love of god...this is a setting that PLAGUES server owners everywhere. (This annoying default true setting is also rampant among Spigot plugins and causes nothing but headaches for server owners that are trying to run a SECURE, STABLE server.)

It is foolish and arrogant (IMHO) to assume that a plugin should always be blindly updated to the latest version without first:

- Validating that the plugin is ACTUALLY COMPATIBLE with the server version first. (DOH!)
- TESTING the new version of the plugin to be sure it's compatible with not only the server, but other plugins as well.

Please change it so auto updates are DISABLED by default instead of enabled. Server owners everywhere will thank you for this simple, time-saving change.

**Comment by JackMD** [comment]
The auto updating "feature" will very soon be removed from EssentialsPE.

**Comment by dktapps** [comment]
I think it's reasonable to have an optional update _notifier_, but if it's such low quality that it doesn't even check compatibility then I guess it's not worth the hassle.

**Comment by JackMD** [comment]
Auto updater disabled as default. Check in #2

**Comment by dktapps** [comment]
this won't have any effect on new installations though, will it?

**Comment by JackMD** [comment]
On new installation. The updater will be disabled. User can opt out to enable it tho. As [here](https://github.com/poggit-orphanage/EssentialsPE/commit/ea9aad4384769ee5deca05df59b92376dbd80294)

**Comment by JackMD** [comment]
Closing since the request is complete.

**Comment by iZeaoGamer** [comment]
But why can't other server owners disable it themselves? Rather than disabling it by default? I'm not complaining, I'm just curious.

**Comment by dktapps** [comment]
Often people don't know or expect it to exist, and then it gjves them a nasty shock when it kicks in.
