### ISSUE TITLE
Home's and warp's arent saving

### ISSUE THREAD

**Issue by BaconOFBurger** [poggit-orphanage/EssentialsPE#4]
#### Description
When im trying to set a home or a warp it's working but after reboot (restart) of my server. ALL homes and warp reset it self. I tried 4 different version of pmmp. Api: 3.0.0, 3.0.1, 3.0.2 and 3.0.3

#### Versions
* PocketMine Version: 1.7-dev1034
* EssentialsPE Version: Dev10 (on Poggit.pmmp.io)
* Game Version: PE

#### Crashdump or console errors
Nope

**Comment by BaconOFBurger** [comment]
And i forgot spawn position too, players are spawning in sky and falling down and dying bruh.

**Comment by JackMD** [comment]
This problem only occurs when your world name in level.dat and the world folder name don't match. Best you can do is to either change your folder name (easy) or change the name of the world in level.dat using NBTExplorer (moderate). Other than that I cannot reproduce this.
